spring:
  application:
    name: xy-demo
  profiles:
    active: ${profiles:local} #local:本地开发环境，dev:开发环境,test:测试环境,prod:生产环境
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 20MB #设置文件上传的大小限制
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true  #出现404错误时，直接抛出异常
  resources:
    add-mappings: false #不建立映射到资源文件

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

mybatis:
  type-aliases-package: cn.xy.demo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: false
  row-bounds-with-count: true

management:
  security:
    enabled: false

#日志文件
logging:
  config: classpath:logback-spring.xml
  level:
    cn:
      xy:
        demo:
          foo:
            mapper: DEBUG



#spring boot应用关闭配置项，关闭命令
endpoints:
  shutdown:
    enabled: true
    sensitive: false #禁用密码验证
    path: /bye-bye