---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Hello World App"
host: "localhost:3000"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  JWT:
    description: "Authorization: Bearer {token}"
    type: "apiKey"
    name: "Authorization"
    in: "header"
security:
  - JWT: []
paths:
  /account/login:
    post:
      summary: "登录"
      description: "登录..."
      security: []
      parameters:
      - in: "body"
        name: "body"
        description: "登录参数"
        required: true
        schema:
          $ref: "#/definitions/LoginBody"
      responses:
        "200":
          description: "登录成功"
          schema:
            $ref: "#/definitions/LoginResponse"
  /account/user:
    get:
      summary: "查询当前用户"
      description: "查询当前用户.."
      responses:
        "200":
          description: "查询成功"
          headers:
            authtoken:
              type: string
              description: 新token续期
          schema:
            $ref: "#/definitions/UserDemo"
        "401":
          $ref: "#/responses/Unauthorized"
        "404":
          $ref: "#/responses/NotFound"
definitions:
  Wxuser:
    type: "object"
    x-isModel: true
    x-plural: "Wxusers"
    description: "微信用户"
    required:
      - "id"
      - "appid"
      - "openid"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "ID"
        uniqueItems: true
      appid:
        type: "string"
        format: "string(32)"
        description: "APPID"
        x-message: "请输入"
        x-showTable: true
      unionid:
        type: "string"
        format: "string(32)"
        description: "UNIONID"
        x-message: "请输入"
      openid:
        type: "string"
        format: "string(32)"
        description: "OPENID"
        x-message: "请输入"
        x-showTable: true
      sessionKey:
        type: "string"
        format: "string(64)"
        description: "SESSIONKEY"
        x-message: "请输入"
      expiresIn:
        type: "string"
        format: "date-time"
        description: "令牌过期时间"
        x-message: "请选择"
      nickname:
        type: "string"
        format: "string(64)"
        description: "昵称"
        x-message: "请输入"
        x-showTable: true
      avatar:
        type: "string"
        format: "string(255)"
        description: "头像"
        x-message: "请输入"
      gender:
        type: "integer"
        format: "int4"
        enum: [1,2,3]
        default: 1
        x-message: "请选择"
        x-showTable: true
        x-showFilter: true
        x-enumMap: {
          0: "未知",
          1: "男",
          2: "女",
        }
        x-description: "性别"
        description: >
          "性别"
            * 0 - 未知
            * 1 - 男
            * 2 - 女
      city:
        type: "string"
        format: "string(32)"
        description: "城市"
        x-message: "请输入"
        x-showTable: true
      province:
        type: "string"
        format: "string(32)"
        description: "省份"
        x-message: "请输入"
      country:
        type: "string"
        format: "string(32)"
        description: "国家"
        x-message: "请输入"
    example:
      "id": "5c984620-04f6-11e9-85d0-950f3b428717"
      "appid": "wx123456"
      "openid": "wx123456"
  UserDemo:
    type: "object"
    description: "用户模型"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        description: "ID"
      name:
        type: "string"
        description: "用户名"
      avatar:
        type: "string"
        description: "头像"
      email:
        type: "string"
        description: "邮箱"
    example:
      name: 'Admin'
      avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png'
      id: '00000001'
      email: 'test@test.com'
  LoginBody:
    type: "object"
    description: "登录参数模型"
    required:
      - "userName"
      - "password"
      - "type"
    properties:
      userName:
        type: "string"
        description: "用户名"
      password:
        type: "string"
        description: "密码"
      type:
        type: "string"
        description: "账户类型"
    example:
      userName: 'admin'
      password: '123456'
      type: 'username'
  LoginResponse:
    type: "object"
    description: "登录返回数据模型"
    required:
      - "status"
      - "type"
      - "currentAuthority"
      - "authtoken"
    properties:
      status:
        type: "string"
        description: "登录状态"
      type:
        type: "string"
        description: "账号类型"
      currentAuthority:
        type: "string"
        description: "当前角色"
      authtoken:
        type: "string"
        description: "秘钥"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
      errors:
        type: "array"
        items:
          $ref: '#/definitions/ErrorItem'
    required:
      - "message"
  ErrorItem:
    type: "object"
    properties:
      errorCode:
        type: "integer"
      errorMessage:
        type: "string"
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
      
      
