---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Hello World App"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /foo:
    post:
      summary: "创建模型"
      description: "创建模型"
      operationId: "createFoo"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
            $ref: "#/definitions/Foo"
      responses:
        default:
          description: "创建成功"
definitions:
  Foo:
    type: "object"
    x-isModel: true
    x-plural: "Foos"
    description: "默认模型"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID"
      name:
        type: "string"
        format: "string(20)"
        description: "名称"
      status:
        type: "integer"
        format: "int4"
        description: "状态"
    example:
      id: 123
      name: "foo"
      status: 1
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
