---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Hello World App"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /user:
    post:
      summary: "创建用户"
      description: "创建用户"
      operationId: "createUser"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
            $ref: "#/definitions/User"
      responses:
        default:
          description: "创建成功"
definitions:
  User:
    type: "object"
    title: "User"
    description: "用户模型"
    required:
      - "id"
      - "username"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID"
      username:
        type: "string"
        format: "string(20)"
        description: "用户名"
      phone:
        type: "string"
        format: "string(11)"
        description: "手机号码"
      userStatus:
        type: "integer"
        format: "int4"
        description: "状态"
    example:
      id: 123
      username: "gabe"
      phone: "13888888888"
  Tag:
    type: "object"
    title: "Tag"
    description: "标签模型"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID"
      name:
        type: "string"
        format: "string(64)"
        description: "标签名"
    example:
      id: 123
      name: "it"
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
